version: "3"
services:
  reverseproxy:
    build:
      context: ./udagram-reverseproxy
    image: reverseproxy-two:v4a
  backend_user:
    build:
      context: ./udagram-api-user
    image: udagram-api-user-two:v4a
  backend_feed:
    build:
      context: ./udagram-api-feed
    image: udagram-api-feed-two:v4a   
  frontend:
    build:
      context: ./udagram-frontend
    image: udagram-frontend-two:local-a
