apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-feed
spec:
  selector:
    matchLabels:
      run: backend-feed
  replicas: 2
  template:
    metadata:
      labels:
        run: backend-feed
    spec:
      containers:
      - name: backend-feed
        image: devopnguyenan88/udagram-api-feed-two:v1a
        imagePullPolicy: Always
        ports:
        - containerPort: 80 
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
        envFrom:
          - secretRef:
              name: env-secret
          - configMapRef:
              name: env-config
          - secretRef:
              name: aws-secret

---
apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: backend-feed